---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pbindal-pipeline-tekton-caches-nodejs-
spec:
  pipelineRef:
    name: pipeline-nodejs
  params:
    - name: repo_url
      value: https://github.com/acemilyalcin/sample-node-project.git
    - name: revision
      value: master
    - name: registry
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)
    - name: cachePatterns
      value: [ "**/workspace/source/package.json" ]
    - name: image
      value: registry.access.redhat.com/ubi9/nodejs-18:latest
  workspaces:
    - name: source
      emptyDir: {}
